
config main 'main'
	option enabled '1'
	option debug '0'

config rtu_device '1'
	option full_duplex_enabled '0'
	option name 'Modbus'
	option device '/dev/rs485'
	option baudrate '115200'
	option flowcontrol 'none'
	option databits '8'
	option parity 'none'
	option stopbits '1'
	option enabled '1'

config rtu_server '2'
	option name 'EnergieMeter'
	option timeout '1'
	option rtu_device '1'
	option frequency 'period'
	option skip_on_many_tmos '0'
	option server_id '154'
	option enabled '1'
	option period '5'

config request_2 '3'
	option broadcast '0'
	option name 'power_received_l1'
	option store_on_change_only '0'
	option enabled '1'
	option reg_count '2'
	option function '4'
	option first_reg '104'
	option data_type '32bit_uint1234'
	option no_brackets '0'

config request_2 '4'
	option broadcast '0'
	option name 'power_delivered_l1'
	option store_on_change_only '0'
	option reg_count '2'
	option function '4'
	option data_type '32bit_uint1234'
	option first_reg '108'
	option enabled '1'
	option no_brackets '0'

config request_2 '5'
	option broadcast '0'
	option name 'total_power_recieved'
	option store_on_change_only '0'
	option reg_count '2'
	option function '4'
	option data_type '32bit_uint1234'
	option first_reg '70'
	option enabled '1'
	option no_brackets '1'

config request_2 '6'
	option broadcast '0'
	option name 'total_power_delivered'
	option store_on_change_only '0'
	option enabled '1'
	option reg_count '2'
	option function '4'
	option no_brackets '1'
	option data_type '32bit_uint1234'
	option first_reg '72'

config rtu_server '7'
	option name 'Accu'
	option timeout '1'
	option rtu_device '1'
	option frequency 'period'
	option skip_on_many_tmos '0'
	option enabled '1'
	option server_id '2'
	option period '5'

config request_7 '8'
	option enabled '0'
	option broadcast '0'
	option name 'SOC'
	option no_brackets '0'
	option store_on_change_only '0'
	option data_type '16bit_int_hi_first'
	option reg_count '1'
	option function '3'
	option first_reg '32105'

